[package]
name = "node-file-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"clap" = { version = "3.1.3", features = ["derive"] }
"turbo-tasks" = { path = "../turbo-tasks" }
"turbopack" = { path = "../turbopack" }
"turbo-tasks-fs" = { path = "../turbo-tasks-fs" }
anyhow = "1.0.47"
async-std = "1.10.0"
