[package]
name = "node-file-trace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node-file-trace"
path = "src/main.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"clap" = { version = "3.1.3", features = ["derive"] }
"turbo-tasks" = { path = "../turbo-tasks" }
"turbo-tasks-memory" = { path = "../turbo-tasks-memory" }
"turbopack" = { path = "../turbopack" }
"turbo-tasks-fs" = { path = "../turbo-tasks-fs" }
anyhow = "1.0.47"
async-std = "1.10.0"
json = "0.12.4"
serde = "1.0.136"

[build-dependencies]
"turbo-tasks-build" = { path = "../turbo-tasks-build" }
