[package]
name = "turbopack-core"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"
browserslist-rs = "=0.11.0"                                        # Keep consistent with preset_env_base
lazy_static = "1.4.0"
patricia_tree = "0.3.1"
preset_env_base = "0.3.2"
rand = "0.8.5"
regex = "1.5.4"
serde = "1.0.136"
serde_json = { version = "1.0.85", features = ["preserve_order"] }
serde_regex = "1.1.0"
sourcemap = "6.0.2"
tokio = "1.11.0"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-hash = { path = "../turbopack-hash" }
url = "2.2.2"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[dev-dependencies]
rstest = "0.12.0"
