[package]
name = "turbopack-core"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
"turbo-tasks" = { path = "../turbo-tasks" }
"turbo-tasks-fs" = { path = "../turbo-tasks-fs" }
async-std = "1.10.0"
regex = "1.5.4"
rand = "0.8.5"
json = "0.12.4"
url = "2.2.2"
indexmap = "1.8.0"
serde = "1.0.136"
serde_regex = "1.1.0"
serde_json = "1.0.81"

[build-dependencies]
"turbo-tasks-build" = { path = "../turbo-tasks-build" }

[dev-dependencies]
rstest = "0.12.0"

