[package]
name = "turbo-tasks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
any_key = "0.1.1"
anyhow = "1.0.47"
async-std = "1.10.0"
bitflags = "1.3.2"
chashmap = "2.2.2"
event-listener = "2.5.2"
lazy_static = "1.4.0"
"turbo-tasks-macros" = { path = "../turbo-tasks-macros" }

[features]
assert_task_state = []