[package]
name = "turbopack-dev-server"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
event-listener = "2.5.2"
futures = "0.3.21"
hyper = { version = "0.14", features = ["full"] }
hyper-tungstenite = "0.8.1"
indexmap = { workspace = true, features = ["serde"] }
lazy_static = "1.4.0"
mime = "0.3.16"
mime_guess = "2.0.4"
parking_lot = "0.12.1"
serde = "1.0.136"
serde_json = "1.0.85"
serde_qs = "0.10.1"
tokio = "1.11.0"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-hash = { path = "../turbopack-hash" }
# TODO remove this dependency
turbopack-cli-utils = { path = "../turbopack-cli-utils" }
urlencoding = "2.1.2"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
