[package]
name = "turbopack-ecmascript"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"
indexmap = "1.8.0"
json = "0.12.4"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.4"
serde = "1.0.136"
serde_json = "1.0.81"
serde_regex = "1.1.0"
#swc_ecma_transforms_module = "0.141.0"
tokio = "1.11.0"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }
turbopack-hash = { path = "../turbopack-hash" }
url = "2.2.2"

swc_core = { version = "0.20.8", features = [
  "ecma_ast",
  "common",
  "common_concurrent",
  "ecma_codegen",
  "ecma_parser",
  "ecma_transforms",
  "ecma_transforms_react",
  "ecma_transforms_module",
  "ecma_quote",
  "ecma_visit",
  "ecma_visit_path",
  "ecma_utils",
] }

[dependencies.num-bigint]
version = "0.4"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
difference = "2.0"
rstest = "0.12.0"
testing = "0.29.1"
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
turbo-tasks-testing = { path = "../turbo-tasks-testing" }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[[bench]]
name = "mod"
harness = false
