[package]
name = "turbopack-ecmascript"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
lazy_static = "1.4.0"
anyhow = "1.0.47"
turbopack-core = { path = "../turbopack-core" }
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
tokio = "1.11.0"
regex = "1.5.4"
rand = "0.8.5"
json = "0.12.4"
swc_atoms = "0.2.13"
swc_ecma_transforms_base = "0.98.0"
swc_ecma_transforms_react="0.134.0"
swc_ecma_codegen = "0.116.0"
swc_ecma_quote = "0.26.2"
swc_ecma_utils = "0.94.0"
url = "2.2.2"
indexmap = "1.8.0"
serde = "1.0.136"
serde_regex = "1.1.0"
serde_json = "1.0.81"
swc_ecma_ast = "0.85.0"
swc_ecma_parser = "0.112.0"

[dependencies.swc_common]
version = "0.24.0"
features = ["concurrent"]

[dependencies.swc_ecma_visit]
version = "0.71.0"
features = ["path"]

[dependencies.num-bigint]
version = "0.4"

[dev-dependencies]
difference = "2.0"
rstest = "0.12.0"
criterion = { version = "0.3.5", features = ["async_tokio"] }
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
turbo-tasks-testing = { path = "../turbo-tasks-testing" }
testing = "0.26.0"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[[bench]]
name = "mod"
harness = false
