[package]
name = "turbopack-ecmascript"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"
indexmap = "1.8.0"
json = "0.12.4"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.4"
serde = "1.0.136"
serde_json = "1.0.81"
serde_regex = "1.1.0"
swc_atoms = "0.3.1"
swc_ecma_ast = "0.89.0"
swc_ecma_codegen = "0.120.0"
swc_ecma_parser = "0.116.0"
swc_ecma_quote = "0.30.0"
swc_ecma_transforms_base = "0.102.0"
swc_ecma_transforms_module = "0.137.0"
swc_ecma_transforms_react = "0.139.0"
swc_ecma_utils = "0.98.0"
tokio = "1.11.0"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }
turbopack-hash = { path = "../turbopack-hash" }
url = "2.2.2"

[dependencies.swc_common]
features = ["concurrent"]
version = "0.26.0"

[dependencies.swc_ecma_visit]
features = ["path"]
version = "0.75.0"

[dependencies.num-bigint]
version = "0.4"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
difference = "2.0"
rstest = "0.12.0"
testing = "0.28.0"
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
turbo-tasks-testing = { path = "../turbo-tasks-testing" }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[[bench]]
name = "mod"
harness = false
