[package]
name = "turbopack-static"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
anyhow = "1.0.47"

turbopack-core = { path = "../turbopack-core" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-hash = { path = "../turbopack-hash" }
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }

serde = "1.0.136"
md4 = "0.10.1"
futures = "0.3.21"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
