[package]
name = "turbo-tasks-fs"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
"turbo-tasks" = { path = "../turbo-tasks" }
"turbo-tasks-memory" = { path = "../turbo-tasks-memory" }
tokio = "1.11.0"
notify = "4.0.17"
concurrent-queue = "1.2.2"
json = "0.12.4"
serde = { version = "1.0.136", features = ["rc"] }

[dev-dependencies]
sha2 = "0.10.2"
rstest = "0.12.0"

[build-dependencies]
"turbo-tasks-build" = { path = "../turbo-tasks-build" }
