[package]
name = "turbo-tasks"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
any_key = "0.1.1"
anyhow = "1.0.47"
async-std = "1.10.0"
bitflags = "1.3.2"
flurry = "0.4.0"
event-listener = "2.5.2"
lazy_static = "1.4.0"
"turbo-tasks-macros" = { path = "../turbo-tasks-macros" }
"weak-table" = "0.3.2"
mopa = "0.2.0"

[build-dependencies]
"turbo-tasks-build" = { path = "../turbo-tasks-build" }

[features]
assert_task_state = []
report_expensive = []