[package]
name = "turbo-tasks-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
"turbo-tasks" = { path = "../turbo-tasks" }
async-std = "1.10.0"
notify = "4.0.17"
