[package]
name = "turbopack-css"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"
serde = "1.0.136"

turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }

swc_atoms = "0.4.2"
swc_css_ast = "0.105.2"
swc_css_codegen = "0.115.1"
swc_css_parser = "0.114.1"
swc_css_utils = "0.102.1"

[dependencies.swc_common]
features = ["concurrent"]
version = "0.27.3"

[dependencies.swc_css_visit]
features = ["path"]
version = "0.104.1"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
