[package]
name = "turbopack-css"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"

turbopack-core = { path = "../turbopack-core" }
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }

swc_atoms = "0.2.13"
serde = "1.0.136"

[dependencies.swc_common]
version = "0.20.1"
features = ["concurrent"]

[dependencies.swc_css]
version = "0.108.0"
features = []

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
