[package]
name = "turbopack"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_persistent_cache = []
bench_against_node_nft = []

[dependencies]
anyhow = "1.0.47"
indexmap = "1.8.0"
json = "0.12.4"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.4"
serde = "1.0.136"
serde_regex = "1.1.0"
tokio = "1.11.0"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }
turbopack-css = { path = "../turbopack-css" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-static = { path = "../turbopack-static" }
url = "2.2.2"
# turbo-tasks-rocksdb could be a dev dependencies, but optional dev dependencies are not allowed
# turbo-tasks-rocksdb = { path = "../turbo-tasks-rocksdb", optional = true }

[dependencies.swc_common]
features = ["concurrent"]
version = "0.27.3"

[dependencies.swc_ecmascript]
features = ["parser", "utils", "visit"]
version = "0.192.0"

[dependencies.num-bigint]
version = "0.4"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
difference = "2.0"
futures = "0.3.21"
rstest = "0.12.0"
rstest_reuse = "0.3.0"
serde_json = "1"
test-generator = "0.3.0"
testing = "0.29.1"
tokio = "1.11.0"
turbo-malloc = { path = "../turbo-malloc" }
turbo-tasks-memory = { path = "../turbo-tasks-memory" }


[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[[bench]]
name = "mod"
harness = false
