[package]
name = "turbopack"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_persistent_cache = ["dep:turbo-tasks-rocksdb"]

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-css = { path = "../turbopack-css" }
turbopack-core = { path = "../turbopack-core" }
tokio = "1.11.0"
regex = "1.5.4"
rand = "0.8.5"
json = "0.12.4"
swc_atoms = "0.2.13"
swc_ecma_transforms_base = "0.94.1"
swc_ecma_loader = { version = "0.32.0", features = ["node"] }
url = "2.2.2"
indexmap = "1.8.0"
serde = "1.0.136"
serde_regex = "1.1.0"
# turbo-tasks-rocksdb could be a dev dependencies, but optional dev dependencies are not allowed
turbo-tasks-rocksdb = { path = "../turbo-tasks-rocksdb", optional = true }

[dependencies.swc_common]
version = "0.20.1"
features = ["concurrent"]

[dependencies.swc_ecmascript]
version = "0.175.0"
features = ["parser", "utils", "visit"]

[dependencies.num-bigint]
version = "0.4"

[dev-dependencies]
tokio = "1.11.0"
difference = "2.0"
rstest = "0.12.0"
rstest_reuse = "0.3.0"
criterion = { version = "0.3.5", features = ["tokio"] }
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
testing = "0.22.0"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[[bench]]
name = "mod"
harness = false
