[package]
name = "turbopack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
"turbo-tasks" = { path = "../turbo-tasks" }
"turbo-tasks-fs" = { path = "../turbo-tasks-fs" }
async-std = "1.10.0"
regex = "1.5.4"
testing = "0.19.1"
rand = "0.8.5"
json = "0.12.4"
swc_atoms = "0.2.9"
swc_ecma_transforms_base = "0.68.0"

[dependencies.swc_common]
version = "0.17.5"
features = ["concurrent"]

[dependencies.swc_ecmascript]
version = "0.133.0"
features = ["parser", "utils", "visit"]

[dev-dependencies]
async-std ={version= "1.10.0",features=["unstable"]}
