[package]
name = "turbo-tasks-testing"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
turbo-tasks = { path = "../turbo-tasks" }
tokio = "1.11.0"
event-listener = "2.5.2"
